### PR TITLE
Fixed BC option indenting

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose
When I was merging the formatting changes from #31 into #33, I inadvertently indented a line that was not supposed to be indented. This broke the BC option. This PR fixes the indenting.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Comment by sseraj** [comment]
I also incremented the version number so I can make a new release after this is merged.

**Review by eirikurj — APPROVED** [review]
Looks good. To prevent this happening again we should put in test that check if the BCs are what they are supposed to be. I think we There should be two tests unittest that check the code and a regression file tests that checks the output cgns file is consistent. I have added an issue #35 for this

**Comment by marcomangano** [comment]
Is this ready to go? Probably (not only) this issue messed up with my `unattachededgesaresymmetry: False` extrusion attempts, looking forward to try the bugfix :)

**Comment by sseraj** [comment]
Yes, this is good to go.

**Comment by eirikurj** [comment]
From my point of view, yes. I was waiting for a second review and perhaps hoping for some types of discussion on how we can prevent this happening. I guess we can direct that to #35. Will merge.

**Pull request merged**
