### PR TITLE
fprettify

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

Formatting the Fortran code with fprettify

## Expected time until merged

1 week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

Current tests pass

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gang525** [comment]
Does a separate PR need to be made so that the git blame history doesn't just have your name on every formatted FORTRAN file?

**Comment by sseraj** [comment]
> Does a separate PR need to be made so that the git blame history doesn't just have your name on every formatted FORTRAN file?

Yes, that's right. We have to add the squashed commit to git-blame-ignore-revs.

**Review by gang525 — APPROVED** [review]
LGTM

**Review by lamkina — APPROVED** [review]
Wow so pretty.

**Comment by lamkina** [comment]
I don't know how to do the git-blame-ignore-revs thing so I'll let @sseraj or @gang525 merge this so I don't screw things up.

**Comment by sseraj** [comment]
> I don't know how to do the git-blame-ignore-revs thing so I'll let @sseraj or @gang525 merge this so I don't screw things up.

We won't know the hash until we merge

**Pull request merged**
